In [20]:
import numpy as np
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [27]:
## import custom library
from model import generate_recommendations


In [77]:
client_id = 1
already_rated = []
k = 5

user_map = np.load("model/user.npy")
item_map = np.load("model\\item.npy")
row_factor = np.load("model\\row.npy")
col_factor = np.load("model\\col.npy")
user_idx = np.searchsorted(user_map, client_id)
user_rated = [np.searchsorted(item_map, i) for i in already_rated]

recommendations = generate_recommendations(user_idx, user_rated, row_factor, col_factor, k)

FileNotFoundError: [Errno 2] No such file or directory: 'model/user.npy'

In [70]:
recommendations

[126, 99, 1142, 284, 407]

In [72]:
article_recommendations = [item_map[i] for i in recommendations]


In [73]:
article_recommendations

[194.0, 22.0, 515.0, 366.0, 757.0]

In [71]:
user_idx

0

## explore numpy array 

In [11]:
user = np.load('user.npy')

In [12]:
user

array([195., 185.,  21., 243., 165., 297., 114., 252., 304.,   5.,  61.,
       285., 199., 209., 223., 302., 121., 193., 290., 233., 118., 166.,
       298., 290., 307.,  94.,  37., 101.,  62., 159.,  49., 300., 224.,
       289.,  96., 156., 180., 277., 275.,   6.,   9., 283., 200., 275.,
       286., 245., 241., 248.,  98., 177., 250.,  80., 259.,  24.,  58.,
        71.,  86., 289.,  41., 291., 114.,  19., 200.,  12., 245., 137.,
       166.,  59.,  56., 222., 188., 242.,  91., 245., 193., 240., 177.,
       253., 292., 126., 224., 298., 224., 275., 290., 221., 266.,  41.,
        10.,  94.,   7., 161.,  86., 278., 144., 118.,  61.,  61.,  27.,
       134.,  31.,  89., 285., 292., 215., 165., 249., 270., 159., 264.,
       197.,  41., 167., 109.,  57.,  89., 270.,  61., 278., 236.,  93.,
       127., 297.,  43., 263., 193.,  71., 221., 249.,  40., 223.,  81.,
       261., 292., 215., 249.,  58., 285., 243.,   6., 173.,  86., 193.,
        81.,  12.,  12., 243., 304.,  94.,  42., 29

In [13]:
item = np.load('item.npy')

In [14]:
item

array([2.410e+02, 3.010e+02, 3.760e+02, 5.000e+01, 3.450e+02, 4.730e+02,
       2.640e+02, 4.640e+02, 4.500e+02, 8.500e+01, 2.560e+02, 1.013e+03,
       2.210e+02, 3.900e+01, 2.800e+01, 7.840e+02, 3.860e+02, 2.730e+02,
       1.041e+03, 1.183e+03, 3.910e+02, 4.850e+02, 1.430e+02, 1.170e+02,
       0.000e+00, 5.450e+02, 9.400e+01, 7.670e+02, 2.760e+02, 2.330e+02,
       2.450e+02, 9.700e+01, 1.920e+02, 8.700e+01, 1.930e+02, 2.730e+02,
       1.080e+03, 6.020e+02, 7.950e+02, 3.100e+01, 1.500e+01, 3.030e+02,
       9.780e+02, 5.630e+02, 3.260e+02, 2.000e+02, 1.136e+03, 2.400e+02,
       3.000e+00, 3.310e+02, 9.900e+01, 4.310e+02, 3.210e+02, 1.800e+02,
       1.950e+02, 6.780e+02, 3.830e+02, 1.420e+02, 4.220e+02, 5.140e+02,
       1.900e+01, 2.870e+02, 2.180e+02, 5.250e+02, 9.180e+02, 2.500e+01,
       2.310e+02, 4.260e+02, 3.030e+02, 2.730e+02, 5.110e+02, 1.400e+01,
       1.048e+03, 4.150e+02, 1.640e+02, 6.890e+02, 2.470e+02, 1.443e+03,
       4.000e+00, 2.280e+02, 2.360e+02, 2.280e+02, 

In [15]:
row = np.load('row.npy')

In [16]:
row

array([[ 5.30595779e-01, -1.79621562e-01, -5.69453649e-02,
         1.05147612e+00,  1.18595064e-02],
       [ 5.77773690e-01, -6.04331493e-01, -1.52576372e-01,
         3.98429543e-01, -7.32299745e-01],
       [ 3.09331208e-01, -8.40904295e-01,  3.39158624e-01,
         1.61478296e-01, -5.35348952e-01],
       [ 7.02210069e-01, -8.57995450e-01, -8.64345670e-01,
        -4.42997217e-02, -8.28183115e-01],
       [ 1.83031529e-01, -1.86380267e-01,  6.08898640e-01,
         9.72053349e-01,  2.13273838e-01],
       [ 5.82266510e-01,  4.14367579e-02, -7.40318596e-01,
         6.57970190e-01,  5.55949867e-01],
       [ 2.84390569e-01, -8.75312626e-01,  3.43665807e-03,
         7.69585073e-01,  7.02130675e-01],
       [-1.86506435e-01, -3.32473367e-01, -8.07676971e-01,
         7.35463083e-01,  5.94013669e-02],
       [ 1.99521691e-01, -4.63028163e-01, -9.51211512e-01,
         5.42519033e-01,  3.64168845e-02],
       [ 2.81262100e-01, -4.62108195e-01,  2.51882970e-01,
         1.01131153e+00